# params.yaml
env:
  env_id: Custom_Pick_Cube
  obs_mode: state
  control_mode: pd_joint_delta_pos
  render_mode: rgb_array
  seed: 42
prepare:
  window_size: 1
  load_count: -1
  transformations: []
  raw_data_path: data/raw/CustomPickCube/
  prepared_data_path: data/prepared/CustomPickCube/
  data_file: augmented.trajectory.h5
train:
  seed: 25
  batch_size: 32
  num_workers: 8
  lr: 0.001
  log_dir: logs/output
  plot_dir: logs/output/plots
  epochs: 30
  model_params:
    num_heads: 6
    hidden_dim: 512
    num_layers: 2
    dropout: 0.5

evaluate:
  render_mode: rgb_array
  video: True